name: Release (Linux)

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - run: cargo build --release

    - run: |
        mkdir dist
        cp target/release/woxi dist/woxi-linux

    - uses: softprops/action-gh-release@v2
      with:
        files: dist/woxi-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
