name: Release (Linux)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # 👈 关键就在这里！

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --release

    - name: Package
      run: |
        mkdir dist
        cp target/release/* dist/

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
